// Test helpers. Expected values come from docs/user-stories.md or from tests/fixtures/expected.json
// (generated by tools/reference_values.py with Python fractions), never from the production calculation.

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = `${resolve(dirname(fileURLToPath(import.meta.url)), '..')}/`;

export const expected = JSON.parse(readFileSync(`${root}tests/fixtures/expected.json`, 'utf8'));
export const casesById = Object.fromEntries(expected.cases.map((c) => [c.id, c]));

/** "n/d" → { n, d } BigInts. */
export function exact(text) {
  const [n, d] = text.split('/');
  return { n: BigInt(n), d: BigInt(d) };
}

/** True when an app rational equals the fixture's exact "n/d" value (cross-multiplication, no floats). */
export function sameValue(actual, exactText) {
  const e = exact(exactText);
  return actual.n * e.d === e.n * actual.d;
}

const storiesMarkdown = readFileSync(`${root}docs/user-stories.md`, 'utf8');

function tableAfter(heading) {
  const start = storiesMarkdown.indexOf(heading);
  if (start < 0) throw new Error(`Heading not found in user-stories.md: ${heading}`);
  const lines = storiesMarkdown.slice(start).split('\n');
  const first = lines.findIndex((line) => line.startsWith('|'));
  const rows = [];
  for (let i = first + 2; i < lines.length && lines[i].startsWith('|'); i += 1) {
    rows.push(lines[i].split('|').slice(1, -1).map((cell) => cell.trim()));
  }
  return rows;
}

const backticked = (cell) => [...cell.matchAll(/`([^`]*)`/g)].map((m) => m[1]);

/** BR-06 error table → [{ key, inputs: [...], message }], excluding ABOVE_MAX (tested via the fixture). */
export function documentedErrors() {
  return tableAfter('**Errors (BR-06), in check order.**')
    .map(([keyCell, examplesCell, message]) => {
      const key = backticked(keyCell)[0];
      const inputs = backticked(examplesCell);
      if (/^blank\b/.test(examplesCell)) inputs.unshift('');
      return { key, inputs, message };
    })
    .filter(({ key }) => key !== 'ABOVE_MAX');
}

/** BR-05 valid-input table → [{ input, paisa }]. */
export function documentedValidInputs() {
  return tableAfter('**Valid input examples (BR-04, BR-05)**').flatMap(([inputCell, parsedCell]) => {
    const inputs = backticked(inputCell);
    const amounts = parsedCell.split('/').map((s) => s.trim());
    return inputs.map((input, i) => {
      const amount = amounts.length === inputs.length ? amounts[i] : amounts[0];
      return { input, paisa: BigInt(amount.replace(/[,.]/g, '')) };
    });
  });
}

/** BR-17 interface wording → { KEY: text }. NOTE_CLIFF is read from US-08-AC5, where its exact text lives. */
export function documentedCopy() {
  const copy = {};
  for (const [keyCell, , text] of tableAfter('**Interface wording (BR-17).**')) {
    const key = backticked(keyCell)[0];
    if (key) copy[key] = text;
  }
  const cliff = storiesMarkdown.match(/surcharge-cliff note \(`NOTE_CLIFF`\)[^"]*"([^"]+)"/);
  if (!cliff) throw new Error('NOTE_CLIFF text not found in US-08-AC5');
  copy.NOTE_CLIFF = cliff[1];
  return copy;
}
